Frontend0430_0.3.6
ottovenliu/taipei-day-trip-website pull request #4
Opened 2021-04-29 18:01 UTC by ottovenliu

不好意思 太晚注意到merge的問題 更新資料已經混到上一個PR中了
不知道怎麼在沒有更新新的物件下再重新發PR 所以簡單刪減一些內容 非常抱歉...QAQ Orz
本周作業已製作完畢
http://35.73.75.176:3000/

2021-04-29 18:03 UTC, ottovenliu commented
姓名:劉碩亭

2021-04-29 18:10 UTC, ottovenliu commented
![Screenshot_20210430-020935599](https://user-images.githubusercontent.com/76770643/116598215-256cc180-a959-11eb-9e5f-96aef9a9654c.jpg)

2021-04-30 01:54 UTC, cwpeng requested changes
以下幾點：
1. 主視覺中的文字和搜尋框的左側請和上下的內容對齊。
2. 景點中的文字和邊框請留一些空間出來。
![35 73 75 176_3000__keyword=%E8%87%BA%E5%8C%97](https://user-images.githubusercontent.com/6104683/116639001-14907000-a99a-11eb-8a99-b87b64dc2c43.png)

2021-04-30 02:10 UTC, cwpeng requested changes
沒有看到問題的修正 ~

2021-04-30 02:56 UTC, ottovenliu commented
不好意思 不知道按鈕的意思就按下去了Orz
目前已經根據老師指示調整好排版問題了

2021-04-30 03:05 UTC, cwpeng approved these changes
OK. 有完成基本要求。

不過你的程式，會在捲動到最後一頁之後，持續地做 API 呼叫，這點雖然不影響表面的運作，但顯然是個問題，建議試著處理好。搜尋一個關鍵字，然後捲動到最後，持續的上下捲動，就會發現這個現象。

2021-04-30 03:19 UTC, merged

2021-04-30 03:21 UTC, ottovenliu commented
好的 後續會在針對這個function的狀態進行優化 謝謝老師的指點~