Guide - Part 3
ottovenliu/taipei-day-trip-website pull request #5
Opened 2021-05-05 19:30 UTC by ottovenliu

劉碩亭
http://35.73.75.176:3000
http://35.73.75.176:3000/attraction/237
作業已完成~再麻煩老師了 
上周所提到的Scroll也已進行優化過了 ~

2021-05-05 19:42 UTC, cwpeng requested changes
大方向還可以，但版面細節落差很大，包括以下幾點，但你可以自己再多仔細和設計稿比對確認更多可能的細節落差：
1. 圖片輪播底下的圈圈不要靠緊底部，留些空間，另外也不要用大紅色來表示。
2. 左右按鈕的箭頭不要緊緊的靠著圓圈的邊緣。
3. 訂購導覽行程區塊中的文字普遍都太小。
4. 選擇時間的上半天和下半天不要換行。
5. 選擇時間的圈圈設計請按照設計稿完成。
6. 景點下方的介紹文字和上方中間有一條淡淡的水平線隔開。
7. 下方景點介紹文字的尺寸和行高。

2021-05-06 03:20 UTC, ottovenliu commented
> 大方向還可以，但版面細節落差很大，包括以下幾點，但你可以自己再多仔細和設計稿比對確認更多可能的細節落差：
> 
> 1. 圖片輪播底下的圈圈不要靠緊底部，留些空間，另外也不要用大紅色來表示。
> 2. 左右按鈕的箭頭不要緊緊的靠著圓圈的邊緣。
> 3. 訂購導覽行程區塊中的文字普遍都太小。
> 4. 選擇時間的上半天和下半天不要換行。
> 5. 選擇時間的圈圈設計請按照設計稿完成。
> 6. 景點下方的介紹文字和上方中間有一條淡淡的水平線隔開。
> 7. 下方景點介紹文字的尺寸和行高。

已根據老師與作業需求進行更新~
1.底部已預留空間,顏色也變更為主題色票按鈕同一色
2.箭頭已縮至圓圈中心
3.文字依照規格書設定為16px
4.已排列至同一排
5.圓圈設計已根據設計稿調整圓圈大小與點擊後色調
6.已加入水平分割線
7.已按照規格書設定成16px 1.5被行高

2021-05-06 04:51 UTC, ottovenliu commented
Frontend0503_2.2.4更新日誌
本次主要更新事項為:
1.增加標題下方淡灰色切割線
2.調整選擇時間上下午區塊間隙為固定距離

2021-05-06 14:39 UTC, cwpeng approved these changes
好哦，有好很多，這樣就可以了 ~

2021-05-06 17:23 UTC, merged