Guide - Part 5
ottovenliu/taipei-day-trip-website pull request #7
Opened 2021-05-21 17:29 UTC by ottovenliu

劉碩亭
http://35.73.75.176:3000/
http://35.73.75.176:3000/attraction/10
http://35.73.75.176:3000/booking
作業已完成~再麻煩老師了

Frontend0517_4.2.1更新日誌
本次主要更新事項為:
1.增設購物流程架構
2.會員購物車互動資料資料庫架設
　　--＞後續嘗試加入多項商品計入與後端資料庫計算
　　--＞有嘗試進行使用cookie進行開發,但經由閱覽資料(資料內容大小的限制)與新聞
　　　　　　(google與apple對於cookie的技術改進)最終判斷依舊採用AJAX技術
3.會員系統功能優化
　3-1 可以點擊的位置，把滑鼠游標用 CSS 改成常見的手勢圖案。(deal)
　3-2 註冊或登入失敗，顯示的提醒訊息以加粗字體做醒目提醒。(deal)
　3-3 註冊成功之後，可以把註冊表單清空，會比較順的感覺。
　　-->暫時未做處理，預計下次作業流程中進行更新

2021-05-21 19:27 UTC, cwpeng requested changes
程式的運作沒問題，但需要你按照 API 文件的規格要求，使用 delete 方法來完成刪除預定行程的動作，而不是使用你自行定義的 action 欄位來決定該採取的動作。

這是一個習慣，我們到職場上之後都得按照規格書來開發，所以請處理好再和我說嘍 ~

2021-05-22 05:44 UTC, ottovenliu commented
已根據老師的指導進行了修改~
再麻煩老師了~~

Frontend0517_4.3.2更新日誌
本次主要更新事項為:
1.依照API格式設定DELETE method request

2021-05-22 15:26 UTC, cwpeng commented
看起來是 OK 了，請記得發 Review Request 給我 ~

2021-05-22 15:27 UTC, ottovenliu commented
> 看起來是 OK 了，請記得發 Review Request 給我 ~

已發送 感謝老師~~~

2021-05-22 15:41 UTC, cwpeng approved these changes
OK.

2021-05-23 04:32 UTC, merged